# Generated by Django 2.0 on 2018-09-29 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 29, 22, 18, 19, 453865)),
        ),
        migrations.AddField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
