# Generated by Django 2.0 on 2018-09-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_remove_todo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
