# Generated by Django 2.0 on 2018-09-30 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20180929_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 30, 1, 13, 28, 297785)),
        ),
    ]
